//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sudoku.Console {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sudoku.Console.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command &apos;{0}&apos; not implemented..
        /// </summary>
        internal static string CommandManager_Execute_CommandNotImplemented {
            get {
                return ResourceManager.GetString("CommandManager_Execute_CommandNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [level].
        /// </summary>
        internal static string GenerateCommand_CommandArgs_level {
            get {
                return ResourceManager.GetString("GenerateCommand_CommandArgs_level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter correct level number..
        /// </summary>
        internal static string GenerateCommand_Execute_IncorectLevelNumber {
            get {
                return ResourceManager.GetString("GenerateCommand_Execute_IncorectLevelNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate a game by level. 1-Easy, 2-Medium, 3-Hard, 4-Samurai.
        /// </summary>
        internal static string GenerateCommand_HelpDescriptioni {
            get {
                return ResourceManager.GetString("GenerateCommand_HelpDescriptioni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	Show this message.
        /// </summary>
        internal static string HelpCommand_HelpDescription {
            get {
                return ResourceManager.GetString("HelpCommand_HelpDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;path&gt;.
        /// </summary>
        internal static string LoadFromFileCommand_CommandArgs_path {
            get {
                return ResourceManager.GetString("LoadFromFileCommand_CommandArgs_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter correct path to file..
        /// </summary>
        internal static string LoadFromFileCommand_Execute_IncorrectPath {
            get {
                return ResourceManager.GetString("LoadFromFileCommand_Execute_IncorrectPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load game from a file.
        /// </summary>
        internal static string LoadFromFileCommand_HelpDescription {
            get {
                return ResourceManager.GetString("LoadFromFileCommand_HelpDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level: {0} ({1}).
        /// </summary>
        internal static string PrintHelper_PrintLevel_Level {
            get {
                return ResourceManager.GetString("PrintHelper_PrintLevel_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score: {0}.
        /// </summary>
        internal static string PrintHelper_PrintLevel_Score {
            get {
                return ResourceManager.GetString("PrintHelper_PrintLevel_Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sudoku&gt; .
        /// </summary>
        internal static string Program_ReadFromConsole_PromptMessage {
            get {
                return ResourceManager.GetString("Program_ReadFromConsole_PromptMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong: {0}.
        /// </summary>
        internal static string Program_Run_SomethingWentWrong {
            get {
                return ResourceManager.GetString("Program_Run_SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one solution for this game..
        /// </summary>
        internal static string SolveCommand_Execute_MoreThanOneSolution {
            get {
                return ResourceManager.GetString("SolveCommand_Execute_MoreThanOneSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No any solution for this game..
        /// </summary>
        internal static string SolveCommand_Execute_NoSolution {
            get {
                return ResourceManager.GetString("SolveCommand_Execute_NoSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, load or generate game..
        /// </summary>
        internal static string SolveCommand_Execute_NotLoadedGame {
            get {
                return ResourceManager.GetString("SolveCommand_Execute_NotLoadedGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	Solve loaded or generated game.
        /// </summary>
        internal static string SolveCommand_HelpDescription {
            get {
                return ResourceManager.GetString("SolveCommand_HelpDescription", resourceCulture);
            }
        }
    }
}
